# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='data_field',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='data_field',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='text',
            new_name='data_field',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='data_field',
        ),
    ]
