# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_studentlecturecomplete_next_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlecturecomplete',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_course_lectures_by_student', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='studentlecturecomplete',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_course_lectures', to=settings.AUTH_USER_MODEL),
        ),
    ]
