# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20170127_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentlecturecomplete',
            options={'ordering': ('-date_completed',)},
        ),
    ]
