# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20170127_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentlecturecomplete',
            options={'get_latest_by': 'date_completed', 'ordering': ('-date_completed',)},
        ),
        migrations.AddField(
            model_name='studentlecturecomplete',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='completed_module_lectures', to='courses.Module'),
            preserve_default=False,
        ),
    ]
