# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20170127_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlecturecomplete',
            name='last',
            field=models.BooleanField(default=False),
        ),
    ]
