# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-11 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20170210_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='module',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='courses.Module'),
            preserve_default=False,
        ),
    ]
