# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-13 09:05
from __future__ import unicode_literals

import courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_quiz_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='order',
            field=courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
