# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-15 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20170214_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='lecture',
        ),
    ]
