# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-15 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_content_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.Lecture'),
            preserve_default=False,
        ),
    ]
