# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_content_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='data_field',
            field=models.CharField(default='', max_length=250),
        ),
    ]
