# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20170220_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='data_field',
            field=models.TextField(default=''),
        ),
    ]
