# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-24 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20170220_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='owner',
        ),
        migrations.AlterField(
            model_name='question',
            name='data_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
