# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-26 09:14
from __future__ import unicode_literals

import courses.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_auto_20170324_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=100, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='Correct?'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.Question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='content',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.Lecture', verbose_name='Content lecture'),
        ),
        migrations.AlterField(
            model_name='content',
            name='order',
            field=courses.fields.OrderField(blank=True, verbose_name='Content order'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Course created datetime'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Course description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_created', to=settings.AUTH_USER_MODEL, verbose_name='Course owner'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Course slug'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses_joined', to=settings.AUTH_USER_MODEL, verbose_name='Course students'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.Subject', verbose_name='Course subject'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Course title'),
        ),
        migrations.AlterField(
            model_name='file',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Content created datetime'),
        ),
        migrations.AlterField(
            model_name='file',
            name='data_field',
            field=models.FileField(upload_to='files', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_related', to=settings.AUTH_USER_MODEL, verbose_name='Content owner'),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Content title'),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Content updated datetime'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Content created datetime'),
        ),
        migrations.AlterField(
            model_name='image',
            name='data_field',
            field=models.FileField(upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_related', to=settings.AUTH_USER_MODEL, verbose_name='Content owner'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Content title'),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Content updated datetime'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.Module', verbose_name='Lecture module'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='order',
            field=courses.fields.OrderField(blank=True, verbose_name='Lecture order'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Lecture title'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.Course', verbose_name='Module course'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, verbose_name='Module description'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=courses.fields.OrderField(blank=True, verbose_name='Module order'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Module title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Content created datetime'),
        ),
        migrations.AlterField(
            model_name='question',
            name='data_field',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_related', to=settings.AUTH_USER_MODEL, verbose_name='Content owner'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Content title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Content updated datetime'),
        ),
        migrations.AlterField(
            model_name='studentlecturecomplete',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed?'),
        ),
        migrations.AlterField(
            model_name='studentlecturecomplete',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_course_lectures_by_student', to='courses.Course', verbose_name='Completed lecture course'),
        ),
        migrations.AlterField(
            model_name='studentlecturecomplete',
            name='date_completed',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Completed lecture datetime'),
        ),
        migrations.AlterField(
            model_name='studentlecturecomplete',
            name='last',
            field=models.BooleanField(default=False, verbose_name='Lecture is last?'),
        ),
        migrations.AlterField(
            model_name='studentlecturecomplete',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_completed_lecture', to='courses.Lecture', verbose_name='Completed lecture'),
        ),
        migrations.AlterField(
            model_name='studentlecturecomplete',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_module_lectures', to='courses.Module', verbose_name='Completed lecture module'),
        ),
        migrations.AlterField(
            model_name='studentlecturecomplete',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_course_lectures', to=settings.AUTH_USER_MODEL, verbose_name='Comleted lecture student'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name="Subject's slug"),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=200, verbose_name="Subject's title"),
        ),
        migrations.AlterField(
            model_name='text',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Content created datetime'),
        ),
        migrations.AlterField(
            model_name='text',
            name='data_field',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='text',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_related', to=settings.AUTH_USER_MODEL, verbose_name='Content owner'),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Content title'),
        ),
        migrations.AlterField(
            model_name='text',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Content updated datetime'),
        ),
        migrations.AlterField(
            model_name='video',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Content created datetime'),
        ),
        migrations.AlterField(
            model_name='video',
            name='data_field',
            field=models.URLField(verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_related', to=settings.AUTH_USER_MODEL, verbose_name='Content owner'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Content title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Content updated datetime'),
        ),
    ]
